title: NewNuke
description: Newnuke is a creating-for-learning PHP framework
show_downloads: true
is_project_page: true
google_analytics:
theme: jekyll-theme-cayman
github:
  zip_url: https://github.com/yeungon/NewNuke/archive/master.zip
  tar_url: https://github.com/yeungon/NewNuke/archive/master.tar.gz
  repository_url: https://github.com/yeungon/newnuke
